
protocol_path: "SNIPRgut_program.xlsx"
calibration_data_path: "calibration_data.yml"

email:
  EmailSettingsFile: ".env"
  ShouldSendEmail: False # When it crashes or is done

phmeter:
  ComPort: 2
  ShouldPrintPhMeterMessages: False # For debugging

networking:
  ShouldPrintSendRecieveMessages: False

pumps:
  ComPort: 1
  BaudRate: 19200
  Diameter: 12.45 # In mm
  InfusionRate: 1.00 # In mL/min
  ShouldPrintPumpMessages: False # For debugging

scheduler:
  ShouldRecordStepsWhileRunning: True
  ShouldInitiallyEnsureCorrectPHBeforeStarting: False
  IncreasedPumpFactorWhenPerformingInitialCorrection: 1
  ShouldPrintSchedulingMessages: True
  AdaptivePumpingActivateAfterNHours: True