

protocol_path: "Minigut.setup_FD.xlsx"
calibration_data_path: "calibration_data.yml"

phmeter:
  ComPort: 2
  ShouldPrintPhMeterMessages: False # For debugging

pumps:
  ComPort: 1
  BaudRate: 19200
  Diameter: 12.45 # In mm
  InfusionRate: 1.00 # In mL/min
  ShouldPrintPumpMessages: False # For debugging

scheduler:
  ShouldInitiallyEnsureCorrectPHBeforeStarting: False
  ShouldPrintSchedulingMessages: True
  ShouldRecordStepsWhileRunning: True # Then even if the system crashes, we can still se the intermediate results
  PhCalibrationDataPath: "calibration_data.yml"